### ISSUE TITLE
images were not published on Docker Hub this morning

### ISSUE THREAD

**Issue by abacaphiliac** [webpt/docker-couchbase-server#15]
a few pull requests were merged today but new images were not published on Docker Hub:
https://hub.docker.com/r/webpt/couchbase-server/tags/

**Comment by kpankonen** [comment]
i am not smart, and forgot to click the automatically build on push button in the docker hub.  it's on now, and i manually triggered builds for both branches.

**Comment by abacaphiliac** [comment]
cool! thanks!

**Comment by abacaphiliac** [comment]
worked great. thanks again!
https://travis-ci.org/abacaphiliac/cache/builds/265021219
